language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - wget https://github.com/box-project/box2/releases/download/2.7.2/box-2.7.2.phar
  - chmod +x box-2.7.2.phar
  - sudo mv box-2.7.2.phar /usr/local/bin/box

install:
  - composer update --no-interaction --prefer-source

script:
  - vendor/bin/phing ci-build

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - php coveralls.phar --verbose --config build/coveralls.yml || true
