build: false
platform: x86
clone_folder: c:\projects\victor

matrix:
  fast_finish: true

cache:
  - c:\php -> appveyor.yml
  - c:\projects\victor\bin -> appveyor.yml
  - c:\projects\victor\vendor -> appveyor.yml

init:
  - SET PATH=c:\php;%PATH%
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  # Install PHP
  - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
  - IF %PHP%==1 cd c:\php
  - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.0.1-Win32-VC14-x86.zip
  - IF %PHP%==1 7z x php-7.0.1-Win32-VC14-x86.zip >nul
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 del /Q *.zip
  # Install Composer
  - IF %PHP%==1 appveyor DownloadFile https://getcomposer.org/composer.phar
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  # Install Xdebug
  - IF %PHP%==1 appveyor DownloadFile http://xdebug.org/files/php_xdebug-2.4.0rc3-7.0-vc14.dll
  - IF %PHP%==1 echo [xdebug] >> php.ini
  - IF %PHP%==1 echo zend_extension=c:\php\php_xdebug-2.4.0rc3-7.0-vc14.dll >> php.ini

  # Go to project folder
  - cd c:\projects\victor

  # Composer
  - composer self-update
  - composer update --no-interaction --prefer-dist

test_script:
  - vendor/bin/phing ci-build
